version: "3"

services:
  web:
    build:
      context: .
    image: {NAME}:{TAG}
    container_name: {NAME}
    environment:
        VIRTUAL_HOST: {SITE_URL}
    expose:
      - "{APP_PORT}"
    network_mode: "bridge"
    tty: {tty}
    restart: {restart}
    command: {command}
