#!groovy

env.APP_NAME=
env.APP_PORT=
env.COMPOSE_VARS_BUILD="APP_PORT NAME TAG SITE_URL"
env.COMPOSE_VARS_TEST="APP_PORT NAME"
env.PATH_REMOTE_DEPLOY="/opt/deploy"
env.SLACK_WEBHOOK_URL=
env.SITE_URL_MASTER=
env.SITE_URL_TEST=


